"""Verify a README generated by /draft-a-readme structurally matches the reference format.

Usage: python verify-format.py <path-to-README.md>
Exits 0 with "PASS" when every structural check is green; exits 1 listing each miss.
"""
import datetime
import re
import sys

path = sys.argv[1]
lines = open(path, encoding="utf-8").read().split("\n")
fails = []


def fail(msg):
    fails.append(msg)


TITLES = [
    "I - Table of Contents", "II - Features", "III - Demonstration",
    "IV - Quick Start", "V - Installation", "VI - Usage",
    "VII - Configuration", "VIII - Reference", "IX - License",
    "X - Authors", "XI - Contact",
]

# 1. Headers present, exact, in order
h2 = [(i, l[3:]) for i, l in enumerate(lines) if l.startswith("## ")]
if [t for _, t in h2] != TITLES:
    fail(f"H2 sequence mismatch: {[t for _, t in h2]}")

# 2. No Unicode roman numerals or bullet separators
blob = "\n".join(lines)
if re.search(r"[Ⅰ-ⅿ•]", blob):
    fail("Unicode roman numeral or bullet character found")

# 3. ToC anchors match the anchor rule
def anchor(title):
    return "#" + title.lower().replace(" - ", "--").replace(" ", "-")

for t in TITLES[1:]:
    want = f"- [{t}]({anchor(t)})"
    if want not in blob:
        fail(f"ToC entry missing/incorrect: {want!r}")

# 4. Header block mechanics
if lines[0] != '<div align="center">':
    fail(f"line 1 is {lines[0]!r}, expected the centered div")
try:
    div_end = lines.index("</div>")
    body = [l for l in lines[1:div_end] if l.strip()]
    bad_indent = [l for l in body if not l.startswith("   ") or l.startswith("    ")]
    if bad_indent:
        fail(f"div lines not 3-space indented: {bad_indent[:2]}")
    if lines[div_end + 1] != "" or lines[div_end + 2] != "---":
        fail("</div> not followed by blank + ---")
    if lines[div_end + 3:div_end + 6] != ["", "", ""]:
        fail("--- not followed by exactly 3 blank lines before ## I")
    if not lines[div_end + 6].startswith("## I - "):
        fail(f"expected ## I after header block, got {lines[div_end + 6]!r}")
except ValueError:
    fail("</div> not found")

# 5. Section breaks: blank, <br>, three blanks, header (sections II..XI)
for i, t in h2:
    if t == TITLES[0]:
        continue
    ctx = lines[i - 5:i]
    if ctx != ["", "<br>", "", "", ""]:
        fail(f"break before {t!r} is {ctx!r}, expected blank/<br>/blank/blank/blank")

# 6. Footer: <br>, ---, *Last Updated: <today>*
foot = re.compile(r"^\*Last Updated: (January|February|March|April|May|June|July|August|September|October|November|December) \d{1,2}, \d{4}\*$")
nonempty = [l for l in lines[-8:] if l != ""]
if len(nonempty) < 3 or nonempty[-3] != "<br>" or nonempty[-2] != "---" or not foot.match(nonempty[-1]):
    fail(f"footer tail wrong: {nonempty[-3:]!r}")
now = datetime.date.today()
if f"*Last Updated: {now:%B} {now.day}, {now.year}*" not in blob:
    fail("footer date is not today's date")

# 7. Badges: for-the-badge everywhere, License and Build last
badges = re.findall(r"https://img\.shields\.io/badge/\S+", blob)
if not badges:
    fail("no shields.io badges")
nofmt = [b for b in badges if "style=for-the-badge" not in b]
if nofmt:
    fail(f"badges missing style=for-the-badge: {nofmt}")
tail_badges = [b for b in badges if "/badge/License-" in b or "/badge/Build-" in b]
if len(tail_badges) < 2 or "License-" not in tail_badges[-2] or "Build-" not in tail_badges[-1]:
    fail(f"License/Build badges not present as the last two: {tail_badges}")

# 8. Facts leaked from the reference example project
leaks = re.findall(r"(?i)ordo astra|berlin52|tsplib|numba|two-opt|traveling salesman|EUC_2D", blob)
if leaks:
    fail(f"reference-example facts leaked into output: {sorted(set(leaks))}")

# 9. Required subsections
for sub in ["### Requirements", "### Dependencies", "### Steps", "### Project layout",
            "### Key entry points", "### External", "| Library | Version | Role |"]:
    if sub not in blob:
        fail(f"missing: {sub!r}")
if not re.search(r"### .+ at a glance", blob):
    fail("missing '### <topic> at a glance' subsection")

print(("FAIL:\n- " + "\n- ".join(fails)) if fails else "PASS: all structural checks green")
sys.exit(1 if fails else 0)
